[[main]]
  name = "Docs"
  url = "/docs/getting-started/"
  identifier = "Docs"
  weight = 10

[[main]]
  name = "Demos"
  url = "/demos/thumbnails/"
  weight = 30

[[main]]
  name = "License"
  url = "/license/"
  weight = 80

[[main]]
  name = "React"
  identifier = "React"
  url = "/docs/react/"
  weight = 50

[[main]]
  name = "Vue"
  identifier = "Vue"
  url = "/docs/vue/"
  weight = 50

[[main]]
  name = "Angular"
  identifier = "Angular"
  url = "/docs/angular/"
  weight = 50


[[social]]
  name = "GitHub"
  identifier = "GitHub"
  url = "https://github.com/sachinchoolur/lightGallery"
  weight = 10
